In [1]:
import numpy as np
import numba

In [2]:
@numba.njit
def _random_mutation_generator(sequence, rate, number_fixed):
    if number_fixed:
        num_mutations = int(rate*len(sequence))
    else:
        num_mutations = np.random.poisson(len(sequence) * rate)
    positions = np.random.choice(np.arange(len(sequence)), num_mutations, replace=False)
    return positions

In [3]:
testseq = 'A' * 100

In [4]:
_random_mutation_generator(testseq, rate=0.1, number_fixed=True)

array([81, 29, 34, 17, 97, 51,  2,  6, 99, 58])

In [5]:
def random_mutation_generator(sequence, rate, num_mutants, number_fixed):
    mutant_list = np.empty(num_mutants, dtype='object')
    for i in range(num_mutants):
        mutant_list[i] = _random_mutation_generator(sequence, rate, number_fixed)
    
    return mutant_list

In [6]:
random_mutation_generator(testseq, rate=0.1, num_mutants=10, number_fixed=True)

array([array([30, 35, 33, 98, 91, 60, 71, 70, 21, 10]),
       array([81, 76, 86, 37, 89, 61, 50, 84, 92, 98]),
       array([33,  4, 80, 35, 37, 60,  7, 11, 51, 63]),
       array([18, 88, 79, 28, 50, 41, 33, 32,  4, 10]),
       array([79, 47, 74, 50, 87, 99,  9, 36, 11, 24]),
       array([73, 90, 44, 56, 10, 43, 61,  0, 99, 54]),
       array([51, 15, 53, 34, 86, 35, 95, 72, 90, 28]),
       array([31, 81, 22, 12, 27, 49, 47, 60, 32,  9]),
       array([35, 51, 20, 30, 90, 27, 38, 63, 13, 49]),
       array([61, 85, 80, 23, 57, 59, 75, 51, 32, 60])], dtype=object)

In [7]:
@numba.njit
def filter_letter(x, letter):
    return x != letter


@numba.njit
def filter_mutation(letter, alph):
    j = 0
    for i in range(alph.size):
        if filter_letter(alph[i], letter):
            j += 1
    result = np.empty(j, dtype=alph.dtype)
    j = 0
    for i in range(alph.size):
        if filter_letter(alph[i], letter):
            result[j] = alph[i]
            j += 1
    return result

def mutate_from_index(sequence, index, allowed_alph):
    seq_list = list(sequence)
    for loci, mutation in index:
        seq_list[loci] = filter_mutation(seq_list[loci], allowed_alph)[mutation].lower()
    return "".join(seq_list)

In [8]:
@numba.njit
def choose_mutation_bias(letter, letters, allowed_alph):
    if letter == 'A':
        _alph = allowed_alph[0]
    elif letter == 'C':
        _alph = allowed_alph[1]
    elif letter == 'G':
        _alph = allowed_alph[2]
    elif letter == 'T':
        _alph = allowed_alph[3]
    
    alph = np.empty(np.sum(_alph), dtype=letters.dtype)
    print(alph)
    i = 0
    j = 0
    for x in _alph:
        if x:
            alph[i] = letters[j]
            i += 1
        j += 1

    return alph

@numba.njit
def make_mutation(letter, letters, allowed_alph):
    alph = choose_mutation_bias(letter, letters, allowed_alph)
    index = np.random.choice(np.arange(len(alph)))
    return alph[index]

def mutate_with_bias(sequence, index, letters, allowed_alph):
    seq_list = list(sequence)
    for loci in index:
        seq_list[loci] = make_mutation(seq_list[loci], letters, allowed_alph).lower()
    return "".join(seq_list)

In [9]:
allowed_alph = np.array([[False, False, False, True],
                         [False, False, True, False],
                         [False, True, False, False],
                         [True, False, False, False]])
letters = np.array(["A", "C", "G", "T"])

mutate_with_bias(testseq, [10], letters, allowed_alph)

: 

: 

In [10]:
allowed_alph = np.array([[False, True, False, True],
                         [False, False, True, False],
                         [False, True, False, False],
                         [True, False, False, False]])
letters = np.array(["A", "C", "G", "T"])

mutate_with_bias(testseq, [10, 20, 30, 40, 50, 60, 70, 80, 90], letters, allowed_alph)

'AAAAAAAAAAcAAAAAAAAAtAAAAAAAAAtAAAAAAAAAcAAAAAAAAAtAAAAAAAAAtAAAAAAAAAcAAAAAAAAAcAAAAAAAAAtAAAAAAAAA'

In [11]:
def mutations_rand(
    sequence, 
    num_mutants,
    rate,
    site_start=0, 
    site_end=None, 
    alph_type="DNA",
    allowed_alph=None,
    number_fixed=False,
    keep_wildtype=False,
):
    
    # Get site to mutate
    
    if site_end==None:
        mutation_window = sequence[site_start:]
    else:
        mutation_window = sequence[site_start:site_end]
    
    # Create list
    if keep_wildtype:
        mutants = np.empty(num_mutants+1, dtype='U{}'.format(len(sequence)))
        mutants[0] = sequence
        i_0 = 1
    else:
        mutants = np.empty(num_mutants, dtype='U{}'.format(len(sequence)))
        i_0 = 0
        
    mutant_indeces = random_mutation_generator(mutation_window, rate, num_mutants, number_fixed)
    if alph_type == "DNA":
        letters = np.array(["A", "C", "G", "T"])
    elif alph_type == "Numeric":
        letters = np.arange(4)
    else:
        raise ValueError("Alphabet type has to be either \"DNA\" or \"Numeric\"")
    
    if allowed_alph is not None:
        for i, x in enumerate(mutant_indeces):
            mutants[i + i_0] = sequence[0:site_start] + mutate_with_bias(mutation_window, x, letters, allowed_alph) + sequence[site_end:]
    else:
        for i, x in enumerate(mutant_indeces):
            mutants[i + i_0] = sequence[0:site_start] + mutate_from_index(mutation_window, x, letters) + sequence[site_end:]
        
    return mutants

In [12]:
allowed_alph = np.array([[False, False, False, True],
                         [False, False, True, False],
                         [False, True, False, False],
                         [True, False, False, False]])

mutations_rand(testseq, 10, rate=0.1, site_start=10, site_end=90, 
    alph_type="DNA",
    allowed_alph=allowed_alph,
    number_fixed=True,
    keep_wildtype=True,
)

array(['AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
       'AAAAAAAAAAAAAAAAAtAtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtAAAAAAtAAttAAAAAAttAAAAAAAAAAA',
       'AAAAAAAAAAAAAAAAtAAAAAAAAAAAAAAAAtAAAAAAtAAAAAtAAAAtAAtAAAAAAAAAAAAAAtAAAAAAAAAAAtAAAAAAAAAAAAAAAAAA',
       'AAAAAAAAAAAAAAtAtAAAAAAAAAAAAAAAAAAAAAtAAAAAtAAAAAtAAAAAAAAAAAAtAAAAAtAAAAAAAAtAAAAAAAAAAAAAAAAAAAAA',
       'AAAAAAAAAAAAAAAAAtAAtAAAAAAAAtAAAttAAAAtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtAAAAAtAAAAAAAAAAAAAAAAAAA',
       'AAAAAAAAAAtAAAAAtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtAAAAttAAAAAAAAAAAAAAAAAAAAAAAAAAAtAAAtAAAtAAAAAAAAAA',
       'AAAAAAAAAAAAttAAAAAAAAAAAAAAAAAAAAAAAttAAAAAAtAAAAAtAAAAAAtAAAAAAAAAAAAAAAtAAAAAAAAAAAAAAAAAAAAAAAAA',
       'AAAAAAAAAAtAAAAAAAAAAAAAAAtAAAAAAAAAAAAAAAAAAtAAAAAAAAtttAAAAAAAAAAAAAAAAAAtAAAAAAAAtAAAAAAAAAAAAAAA',
       'AAAAAAAAAAAAAAAAAAAAAAtAtAAAAAAtAAAtAAAAAAtAAAAtAAAAAAAAAAtAAAAAAAAtAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
 

In [13]:
allowed_alph = np.array([[False, True, False, True],
                         [False, False, True, False],
                         [False, True, False, False],
                         [True, False, False, False]])

mutations_rand(testseq, 10, rate=0.1, site_start=10, site_end=90, 
    alph_type="DNA",
    allowed_alph=allowed_alph,
    number_fixed=True,
    keep_wildtype=True,
)

array(['AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
       'AAAAAAAAAAActAAtAAAAAAAAAAtAAAAAAAcAAAAAAAAAAAAAAAAAAAcAAAAtAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
       'AAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAtAAAAAAcAAAAAAAAAAAcAAAAtAAAAtAAAcAAAAAtAAAAAAAAAAAAA',
       'AAAAAAAAAAAAAAtAAAAAAAAAtAAAAAcAtAtAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAttAAAAAAAAAAA',
       'AAAAAAAAAAAAAAAAAAAAAtAAAtAAAAAAAAAAAAAAAAAAAAAAAAAAcAtAAAAAcAAAActAAAAtAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
       'AAAAAAAAAAAAtAAAAAAtttAtAAAAAAAAAAAAAAAcAAcAAAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
       'AAAAAAAAAAAAAcAAAAAActAAAAAAAAAAAAAtAAAAAAAAAAttAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAA',
       'AAAAAAAAAAAAAAAAAAAAtAAtAAAAAAAAAcAAAAAAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAcAcAAAAAAAAAAAAccAAAAAAAAAAAAA',
       'AAAAAAAAAAAAAAAAAAAAAAAAccAAtAAAAAAAAAAAAAtAAAAAAAAAAAAAAAAAAAcAAAAAAAAAAAAtAAcAAAcAAAAAAAAAAAAAAAAA',
 

In [14]:
testseq = 'ACGT' * 25

allowed_alph = np.array([[False, False, False, True],
                         [False, False, True, False],
                         [False, True, False, False],
                         [True, False, False, False]])

mutations_rand(testseq, 10, rate=0.1, site_start=10, site_end=90, 
    alph_type="DNA",
    allowed_alph=allowed_alph,
    number_fixed=True,
    keep_wildtype=True,
)

array(['ACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGT',
       'ACGTACGTACGTACGTAgGTACGTACGTACGaACcTACGTtCGTACcTACGTACGTACGTACcTACGTACGTAgGTACGTACcTACGTACGTACGTACGT',
       'ACGTACGTACGTACGTACGTACGTACcTACGTACGTACGaACGTACGaACGTACGTACGTtCcTAgcTACGTACGTACcTACGTACGTACGTACGTACGT',
       'ACGTACGTACcaACGaACGTACGTtCGTACGTACGTACGaAgGTACGTACcTACGTACGTACGTACGTACGTACGTACcTACGTACGTACGTACGTACGT',
       'ACGTACGTACGTACGaACGTAgGTACGTACGTACGTACGTACGTAgGTACcTACGTtCGTACGTACGTAgGTtCGTtCGTACGTACGTACGTACGTACGT',
       'ACGTACGTACGTACGTACGTACGTACGTACGTtCGTAgGTAgcTACcTACGTACGTACGTACGTACcaACcTACGTACGTACGTACGTACGTACGTACGT',
       'ACGTACGTACGTACGaAgGaACcTACcTACcTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTACGTAgGTAgGTACGTACGTACGTACGT',
       'ACGTACGTACGTtgGaACGTACGTACcTACGTACGTACGTACGTACGaACGTACcaACGTACGTACGaACGTACGTACGTACGTACGTACGTACGTACGT',
       'ACGTACGTACGTACGTAgGTACGTACGTAgGTACGTtCGTACGTACGaACGTACGaACGTACGTACGTACGTACGTACcTACGaAgGTACGTACGTACGT',
 

In [17]:
testseq = 'ACGT' * 25

allowed_alph = np.array([[False, False, False, True],
                         [False, False, True, False],
                         [False, True, False, False],
                         [False, False, False, False]])

mutations_rand(testseq, 10, rate=0.1, site_start=10, site_end=90, 
    alph_type="DNA",
    allowed_alph=allowed_alph,
    number_fixed=True,
    keep_wildtype=True,
)

: 

: 